CREATE TABLE users (
PRIMARY KEY (id),
id BIGINT NOT NULL AUTO_INCREMENT,
name VARCHAR(25) NOT NULL,
cpf VARCHAR(25) NOT NULL,
date_birth VARCHAR(25) NOT NULL,
email VARCHAR(25),
password VARCHAR(35),
UNIQUE (cpf)
);